/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empguadalupe.Menu.Evaluacion.arranque;

import empguadalupe.Menu.Menu1;
import java.awt.Color;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author lzambrs
 */
public class CondicionesInicialesEva extends javax.swing.JFrame {

    int contadorGeneral;
    int contErrores;
    //en las condiciones iniciales se da un if para tener un control de cuantas preguntas va respuestas y para que no pueda 
    //pasar a la siguiente prueba sin completar las 6 preguntas. cuando se ejecuta el for es para escoger cuales son 
    //las 5 preguntas a desaparecer 

    public CondicionesInicialesEva() {
        initComponents();
          this.setResizable(false);

        Metodos generar = new Metodos();

        Stack<Integer> numero = generar.generaNumeroAleatoriosin(1, 45);
        int numero1;

        String nomlabel, nomlabel1, nomlabel2, nomlabel3, nomlabel4, nomlabel5, nomlabel6;
        String labels[] = new String[6];
        int i;
        // String label1,label2,label3,label4,label5,label6;
        for (i = 0; i <= 5; i++) {
            numero1 = numero.get(i);
            labels = textos(numero1, i);
            System.out.println(numero1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labe2 = new javax.swing.JLabel();
        labe1 = new javax.swing.JLabel();
        labe3 = new javax.swing.JLabel();
        labe4 = new javax.swing.JLabel();
        labe7 = new javax.swing.JLabel();
        labe14 = new javax.swing.JLabel();
        labe6 = new javax.swing.JLabel();
        labe5 = new javax.swing.JLabel();
        labe13 = new javax.swing.JLabel();
        labe12 = new javax.swing.JLabel();
        labe11 = new javax.swing.JLabel();
        labe10 = new javax.swing.JLabel();
        labe9 = new javax.swing.JLabel();
        labe8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        labe18 = new javax.swing.JLabel();
        labe17 = new javax.swing.JLabel();
        labe16 = new javax.swing.JLabel();
        labe15 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        labelt = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        labe20 = new javax.swing.JLabel();
        labe19 = new javax.swing.JLabel();
        labe21 = new javax.swing.JLabel();
        labe22 = new javax.swing.JLabel();
        labe24 = new javax.swing.JLabel();
        labe23 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        labet2 = new javax.swing.JLabel();
        labe26 = new javax.swing.JLabel();
        labe25 = new javax.swing.JLabel();
        labe27 = new javax.swing.JLabel();
        labe28 = new javax.swing.JLabel();
        labe31 = new javax.swing.JLabel();
        labe30 = new javax.swing.JLabel();
        labe29 = new javax.swing.JLabel();
        labe34 = new javax.swing.JLabel();
        labe33 = new javax.swing.JLabel();
        labe32 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        labet3 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        labe36 = new javax.swing.JLabel();
        labe35 = new javax.swing.JLabel();
        labe37 = new javax.swing.JLabel();
        labe38 = new javax.swing.JLabel();
        labe41 = new javax.swing.JLabel();
        labe40 = new javax.swing.JLabel();
        labe39 = new javax.swing.JLabel();
        labe42 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        labe44 = new javax.swing.JLabel();
        labe43 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 20, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 20, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 20, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 20, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 20, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 20, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 20, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 20, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 20, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 20, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 20, 20));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 20, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 20, 20));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 20, 20));

        labe2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe2.setForeground(new java.awt.Color(255, 255, 255));
        labe2.setText("VOLTAJES DE CONTROL DISPONIBLES ");
        labe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe2MouseClicked(evt);
            }
        });
        getContentPane().add(labe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, 20));

        labe1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe1.setForeground(new java.awt.Color(255, 255, 255));
        labe1.setText("SECUENCIA DE PARO INACTIVAS ");
        labe1.setFocusable(false);
        labe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe1MouseClicked(evt);
            }
        });
        getContentPane().add(labe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 280, 20));

        labe3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe3.setForeground(new java.awt.Color(255, 255, 255));
        labe3.setText("VOLTAJES AUXILIARES NORMALES U ");
        labe3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe3MouseClicked(evt);
            }
        });
        getContentPane().add(labe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 270, 20));

        labe4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe4.setForeground(new java.awt.Color(255, 255, 255));
        labe4.setText("SELECTORES EN POSICION NORMAL ");
        labe4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe4MouseClicked(evt);
            }
        });
        getContentPane().add(labe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, 20));

        labe7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe7.setForeground(new java.awt.Color(255, 255, 255));
        labe7.setText("ENCLAVAMIENTO DISTRUIBUIDOR RETIRADO");
        labe7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe7MouseClicked(evt);
            }
        });
        getContentPane().add(labe7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, 20));

        labe14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe14.setForeground(new java.awt.Color(255, 255, 255));
        labe14.setText("VÀLVULA ESFÈRICA ADMISION LISTA");
        labe14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe14MouseClicked(evt);
            }
        });
        getContentPane().add(labe14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 240, 20));

        labe6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe6.setForeground(new java.awt.Color(255, 255, 255));
        labe6.setText("ALABES MOVILES OK ");
        labe6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe6MouseClicked(evt);
            }
        });
        getContentPane().add(labe6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 240, 20));

        labe5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe5.setForeground(new java.awt.Color(255, 255, 255));
        labe5.setText("JUNTA INFLABLE MTT DESAPLICADA ");
        labe5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe5MouseClicked(evt);
            }
        });
        getContentPane().add(labe5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 270, 20));

        labe13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe13.setForeground(new java.awt.Color(255, 255, 255));
        labe13.setText("REGULADOR VELOCIDAD TURBINA LISTO*");
        labe13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe13MouseClicked(evt);
            }
        });
        getContentPane().add(labe13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 240, 20));

        labe12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe12.setForeground(new java.awt.Color(255, 255, 255));
        labe12.setText("SISTEMA HIDRAULICO TURBINA LISTO*");
        labe12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe12MouseClicked(evt);
            }
        });
        getContentPane().add(labe12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 240, 20));

        labe11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe11.setForeground(new java.awt.Color(255, 255, 255));
        labe11.setText("SISTEMA DE FRENOS LISTO*");
        labe11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe11MouseClicked(evt);
            }
        });
        getContentPane().add(labe11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 240, 20));

        labe10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe10.setForeground(new java.awt.Color(255, 255, 255));
        labe10.setText("RESET RELES DE BLOQUEO*");
        labe10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe10MouseClicked(evt);
            }
        });
        getContentPane().add(labe10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 240, 20));

        labe9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe9.setForeground(new java.awt.Color(255, 255, 255));
        labe9.setText("NIVEL ACEITE COJIN SUPERIOR NORMAL");
        labe9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe9MouseClicked(evt);
            }
        });
        getContentPane().add(labe9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 240, 20));

        labe8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe8.setForeground(new java.awt.Color(255, 255, 255));
        labe8.setText("NIVEL DE ACEITE COJIN INFERIOR NORMAL");
        labe8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe8MouseClicked(evt);
            }
        });
        getContentPane().add(labe8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 270, 20));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 240, 20));

        labe18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe18.setForeground(new java.awt.Color(255, 255, 255));
        labe18.setText("VIBRACIONES UNIDAD X SIN DISPARO");
        labe18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe18MouseClicked(evt);
            }
        });
        getContentPane().add(labe18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 240, 20));

        labe17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe17.setForeground(new java.awt.Color(255, 255, 255));
        labe17.setText("SECCIONADOR GENERADOR CERRADO*");
        labe17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe17MouseClicked(evt);
            }
        });
        getContentPane().add(labe17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 240, 20));

        labe16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe16.setForeground(new java.awt.Color(255, 255, 255));
        labe16.setText("MCB POTENCIAL RED NORMAL*");
        labe16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe16MouseClicked(evt);
            }
        });
        getContentPane().add(labe16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 240, 20));

        labe15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe15.setForeground(new java.awt.Color(255, 255, 255));
        labe15.setText("SISTEMA REGULADOR DE VOLTAJE LISTO*");
        labe15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe15MouseClicked(evt);
            }
        });
        getContentPane().add(labe15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 240, 20));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 20, 20));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 20, 20));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 20, 20));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 20, 20));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("GUADALUPE IV:ENCLAVAMIENTOS UNIDAD X SECUENCIA DE ARRANQUE");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 670, 30));

        labelt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelt.setForeground(new java.awt.Color(255, 255, 255));
        labelt.setText("DESDE PARO TOTAL");
        labelt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(labelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, 40));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 20, 20));

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 20, 20));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 20, 20));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 20, 20));

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 20, 20));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 20, 20));

        labe20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe20.setForeground(new java.awt.Color(255, 255, 255));
        labe20.setText("CO2 NO ACTIVADO*");
        labe20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe20MouseClicked(evt);
            }
        });
        getContentPane().add(labe20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 240, 20));

        labe19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe19.setForeground(new java.awt.Color(255, 255, 255));
        labe19.setText("VALVULA DE ALIVIO CERRADA*");
        labe19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe19MouseClicked(evt);
            }
        });
        getContentPane().add(labe19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 240, 20));

        labe21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe21.setForeground(new java.awt.Color(255, 255, 255));
        labe21.setText("REGULADOR DE TENSION EN AUTOMATICO*");
        labe21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe21MouseClicked(evt);
            }
        });
        getContentPane().add(labe21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 240, 20));

        labe22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe22.setForeground(new java.awt.Color(255, 255, 255));
        labe22.setText("REGULADOR DE TENSION EN REMOTO");
        labe22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe22MouseClicked(evt);
            }
        });
        getContentPane().add(labe22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 240, 20));

        labe24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe24.setForeground(new java.awt.Color(255, 255, 255));
        labe24.setText("DISTRIBUIDOR CERRADO");
        labe24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe24MouseClicked(evt);
            }
        });
        getContentPane().add(labe24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 240, 20));

        labe23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe23.setForeground(new java.awt.Color(255, 255, 255));
        labe23.setText("SISTEMA INTERRUPTOR GENERADOR LISTO");
        labe23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe23MouseClicked(evt);
            }
        });
        getContentPane().add(labe23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 240, 20));

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 310, 190));

        labet2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labet2.setForeground(new java.awt.Color(255, 255, 255));
        labet2.setText("DESDE PARO TOTAL");
        labet2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(labet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 310, 40));

        labe26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe26.setForeground(new java.awt.Color(255, 255, 255));
        labe26.setText("VOLTAJES DE CONTROL DISPONIBLES*");
        labe26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe26MouseClicked(evt);
            }
        });
        getContentPane().add(labe26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 240, 20));

        labe25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe25.setForeground(new java.awt.Color(255, 255, 255));
        labe25.setText("SECUENCIA DE PARO INACTIVAS");
        labe25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe25MouseClicked(evt);
            }
        });
        getContentPane().add(labe25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 240, 20));

        labe27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe27.setForeground(new java.awt.Color(255, 255, 255));
        labe27.setText("VOLTAJES AUXILIARES NORMALES Ux *");
        labe27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe27MouseClicked(evt);
            }
        });
        getContentPane().add(labe27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 240, 20));

        labe28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe28.setForeground(new java.awt.Color(255, 255, 255));
        labe28.setText("SELECTORES EN POSICION NORMAL*");
        labe28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe28MouseClicked(evt);
            }
        });
        getContentPane().add(labe28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 240, 20));

        labe31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe31.setForeground(new java.awt.Color(255, 255, 255));
        labe31.setText("ENCLAVAMIENTO DISTRUIBUIDOR RETIRADO*");
        labe31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe31MouseClicked(evt);
            }
        });
        getContentPane().add(labe31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 240, 20));

        labe30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe30.setForeground(new java.awt.Color(255, 255, 255));
        labe30.setText("ALABES MOVILES OK");
        labe30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe30MouseClicked(evt);
            }
        });
        getContentPane().add(labe30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 240, 20));

        labe29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe29.setForeground(new java.awt.Color(255, 255, 255));
        labe29.setText("JUNTA INFLABLE MTT DESAPLICADA*");
        labe29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe29MouseClicked(evt);
            }
        });
        getContentPane().add(labe29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 240, 20));

        labe34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe34.setForeground(new java.awt.Color(255, 255, 255));
        labe34.setText("RESET RELES DE BLOQUEO*");
        labe34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe34MouseClicked(evt);
            }
        });
        getContentPane().add(labe34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 240, 20));

        labe33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe33.setForeground(new java.awt.Color(255, 255, 255));
        labe33.setText("NIVEL ACEITE COJIN SUPERIOR NORMAL");
        labe33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe33MouseClicked(evt);
            }
        });
        getContentPane().add(labe33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 240, 20));

        labe32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe32.setForeground(new java.awt.Color(255, 255, 255));
        labe32.setText("NIVEL DE ACEITE COJIN INFERIOR NORMAL");
        labe32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe32MouseClicked(evt);
            }
        });
        getContentPane().add(labe32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 240, 20));

        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 240, 20));

        labet3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labet3.setForeground(new java.awt.Color(255, 255, 255));
        labet3.setText("DESDE MARCHA");
        labet3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(labet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 310, 40));

        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 20, 20));

        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 20, 20));

        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 20, 20));

        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 20, 20));

        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 20, 20));

        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 20, 20));

        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 20, 20));

        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 20, 20));

        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 20, 20));

        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 20, 20));

        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 20, 20));

        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 20, 20));

        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 20, 20));

        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 20, 20));

        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 20, 20));

        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 20, 20));

        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 20, 20));

        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 20, 20));

        labe36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe36.setForeground(new java.awt.Color(255, 255, 255));
        labe36.setText("VOLTAJES DE CONTROL DISPONIBLES*");
        labe36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe36MouseClicked(evt);
            }
        });
        getContentPane().add(labe36, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 240, 20));

        labe35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe35.setForeground(new java.awt.Color(255, 255, 255));
        labe35.setText("SECUENCIA DE PARO INACTIVAS");
        labe35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe35MouseClicked(evt);
            }
        });
        getContentPane().add(labe35, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 240, 20));

        labe37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe37.setForeground(new java.awt.Color(255, 255, 255));
        labe37.setText("NORMAL AUXILIAR DE LOS VOLTAJES UX");
        labe37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe37MouseClicked(evt);
            }
        });
        getContentPane().add(labe37, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 240, 20));

        labe38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe38.setForeground(new java.awt.Color(255, 255, 255));
        labe38.setText("SELECTORES EN POSICION NORMAL*");
        labe38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe38MouseClicked(evt);
            }
        });
        getContentPane().add(labe38, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 240, 20));

        labe41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe41.setForeground(new java.awt.Color(255, 255, 255));
        labe41.setText("CO2 NO ACTIVADO*");
        labe41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe41MouseClicked(evt);
            }
        });
        getContentPane().add(labe41, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 240, 20));

        labe40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe40.setForeground(new java.awt.Color(255, 255, 255));
        labe40.setText("SISTEMA DE FRENOS LISTO*");
        labe40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe40MouseClicked(evt);
            }
        });
        getContentPane().add(labe40, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 240, 20));

        labe39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe39.setForeground(new java.awt.Color(255, 255, 255));
        labe39.setText("RESET RELES BLOQUEO*");
        labe39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe39MouseClicked(evt);
            }
        });
        getContentPane().add(labe39, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 240, 20));

        labe42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe42.setForeground(new java.awt.Color(255, 255, 255));
        labe42.setText("SISTEMA INTERRUPTOR GENERADOR NORMAL");
        labe42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe42MouseClicked(evt);
            }
        });
        getContentPane().add(labe42, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 260, 20));

        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 240, 20));

        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 310, 250));

        jLabel96.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("DESDE ENERGIZADO");
        jLabel96.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 310, 40));

        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 20, 20));

        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 20, 20));

        labe44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe44.setForeground(new java.awt.Color(255, 255, 255));
        labe44.setText("PUERTAS INTERRUPTOR MAQUINA CERRADAS*");
        labe44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe44MouseClicked(evt);
            }
        });
        getContentPane().add(labe44, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 270, 20));

        labe43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labe43.setForeground(new java.awt.Color(255, 255, 255));
        labe43.setText("SINCRONIZADOR DISPONIBLE*");
        labe43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labe43MouseClicked(evt);
            }
        });
        getContentPane().add(labe43, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 240, 20));

        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 310, 80));

        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 310, 310));

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("DESDE ENERGIZADO");
        jLabel102.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 310, 40));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 50, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 50, 40));

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("4");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 50, 40));

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("1");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 50, 40));

        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 20, 20));

        jLabel106.setForeground(new java.awt.Color(255, 255, 255));
        jLabel106.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 20, 20));

        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 20, 20));

        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 20, 20));

        jLabel109.setForeground(new java.awt.Color(255, 255, 255));
        jLabel109.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 20, 20));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 550));

        jLabel104.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgfondo/color.png"))); // NOI18N
        getContentPane().add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (contadorGeneral >= 6) {
            CondicionesIniciales2 condi2 = new CondicionesIniciales2();
            condi2.setVisible(true);
            ArranqueEva arra = new ArranqueEva();
            arra.pu2 = contErrores;
            dispose();
        } else {
            close();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    String label2;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void labe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe1MouseClicked

        if (select[1] == true) {
            boolean respun = false;
            respun = generarpreguntas(1);
            if (respun == true) {
                labe1.setForeground(Color.WHITE);
                select[1] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe1MouseClicked

    private void labe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe2MouseClicked
        if (select[2] == true) {
            boolean respun = false;
            respun = generarpreguntas(2);
            if (respun == true) {
                labe2.setForeground(Color.WHITE);
                select[2] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe2MouseClicked

    private void labe3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe3MouseClicked
        if (select[3] == true) {
            boolean respun = false;
            respun = generarpreguntas(3);
            if (respun == true) {
                labe3.setForeground(Color.WHITE);
                select[3] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe3MouseClicked

    private void labe4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe4MouseClicked
        if (select[4] == true) {
            boolean respun = false;
            respun = generarpreguntas(4);
            if (respun == true) {
                labe4.setForeground(Color.WHITE);
                select[4] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe4MouseClicked

    private void labe5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe5MouseClicked
        if (select[5] == true) {
            boolean respun = false;
            respun = generarpreguntas(5);
            if (respun == true) {
                labe5.setForeground(Color.WHITE);
                select[5] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe5MouseClicked

    private void labe6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe6MouseClicked
        if (select[6] == true) {
            boolean respun = false;
            respun = generarpreguntas(6);
            if (respun == true) {
                labe6.setForeground(Color.WHITE);
                select[6] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe6MouseClicked

    private void labe7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe7MouseClicked
        if (select[7] == true) {
            boolean respun = false;
            respun = generarpreguntas(7);
            if (respun == true) {
                labe7.setForeground(Color.WHITE);
                select[7] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe7MouseClicked

    private void labe8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe8MouseClicked
        if (select[8] == true) {
            boolean respun = false;
            respun = generarpreguntas(8);
            if (respun == true) {
                labe8.setForeground(Color.WHITE);
                select[8] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe8MouseClicked

    private void labe9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe9MouseClicked
        if (select[9] == true) {
            boolean respun = false;
            respun = generarpreguntas(9);
            if (respun == true) {
                labe9.setForeground(Color.WHITE);
                select[9] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe9MouseClicked

    private void labe10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe10MouseClicked
        if (select[10] == true) {
            boolean respun = false;
            respun = generarpreguntas(10);
            if (respun == true) {
                labe10.setForeground(Color.WHITE);
                select[10] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }

    }//GEN-LAST:event_labe10MouseClicked

    private void labe11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe11MouseClicked
        if (select[11] == true) {
            boolean respun = false;
            respun = generarpreguntas(11);
            if (respun == true) {
                labe11.setForeground(Color.WHITE);
                select[11] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe11MouseClicked

    private void labe12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe12MouseClicked
        if (select[12] == true) {
            boolean respun = false;
            respun = generarpreguntas(12);
            if (respun == true) {
                labe12.setForeground(Color.WHITE);
                select[12] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe12MouseClicked

    private void labe13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe13MouseClicked
        if (select[13] == true) {
            boolean respun = false;
            respun = generarpreguntas(13);
            if (respun == true) {
                labe13.setForeground(Color.WHITE);
                select[13] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe13MouseClicked

    private void labe14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe14MouseClicked
        if (select[14] == true) {
            boolean respun = false;
            respun = generarpreguntas(14);
            if (respun == true) {
                labe14.setForeground(Color.WHITE);
                select[14] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe14MouseClicked

    private void labe15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe15MouseClicked
        if (select[15] == true) {
            boolean respun = false;
            respun = generarpreguntas(15);
            if (respun == true) {
                labe15.setForeground(Color.WHITE);
                select[15] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe15MouseClicked

    private void labe16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe16MouseClicked
        if (select[16] == true) {
            boolean respun = false;
            respun = generarpreguntas(16);
            if (respun == true) {
                labe16.setForeground(Color.WHITE);
                select[16] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe16MouseClicked

    private void labe17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe17MouseClicked
        if (select[17] == true) {
            boolean respun = false;
            respun = generarpreguntas(17);
            if (respun == true) {
                labe17.setForeground(Color.WHITE);
                select[17] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe17MouseClicked

    private void labe18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe18MouseClicked
        if (select[18] == true) {
            boolean respun = false;
            respun = generarpreguntas(18);
            if (respun == true) {
                labe18.setForeground(Color.WHITE);
                select[18] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe18MouseClicked

    private void labe19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe19MouseClicked
        if (select[19] == true) {
            boolean respun = false;
            respun = generarpreguntas(19);
            if (respun == true) {
                labe19.setForeground(Color.WHITE);
                select[19] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe19MouseClicked

    private void labe20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe20MouseClicked
        if (select[20] == true) {
            boolean respun = false;
            respun = generarpreguntas(20);
            if (respun == true) {
                labe20.setForeground(Color.WHITE);
                select[20] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe20MouseClicked

    private void labe21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe21MouseClicked
        if (select[21] == true) {
            boolean respun = false;
            respun = generarpreguntas(21);
            if (respun == true) {
                labe21.setForeground(Color.WHITE);
                select[21] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe21MouseClicked

    private void labe22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe22MouseClicked
        if (select[22] == true) {
            boolean respun = false;
            respun = generarpreguntas(22);
            if (respun == true) {
                labe22.setForeground(Color.WHITE);
                select[22] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe22MouseClicked

    private void labe23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe23MouseClicked
        if (select[23] == true) {
            boolean respun = false;
            respun = generarpreguntas(23);
            if (respun == true) {
                labe23.setForeground(Color.WHITE);
                select[23] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe23MouseClicked

    private void labe24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe24MouseClicked
        if (select[24] == true) {
            boolean respun = false;
            respun = generarpreguntas(24);
            if (respun == true) {
                labe24.setForeground(Color.WHITE);
                select[24] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe24MouseClicked

    private void labe25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe25MouseClicked
        if (select[25] == true) {
            boolean respun = false;
            respun = generarpreguntas(25);
            if (respun == true) {
                labe25.setForeground(Color.WHITE);
                select[25] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe25MouseClicked

    private void labe26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe26MouseClicked
        if (select[26] == true) {
            boolean respun = false;
            respun = generarpreguntas(26);
            if (respun == true) {
                labe26.setForeground(Color.WHITE);
                select[26] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe26MouseClicked

    private void labe27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe27MouseClicked
        if (select[27] == true) {
            boolean respun = false;
            respun = generarpreguntas(27);
            if (respun == true) {
                labe27.setForeground(Color.WHITE);
                select[27] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe27MouseClicked

    private void labe28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe28MouseClicked
        if (select[28] == true) {
            boolean respun = false;
            respun = generarpreguntas(28);
            if (respun == true) {
                labe28.setForeground(Color.WHITE);
                select[28] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe28MouseClicked

    private void labe29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe29MouseClicked
        if (select[29] == true) {
            boolean respun = false;
            respun = generarpreguntas(29);
            if (respun == true) {
                labe29.setForeground(Color.WHITE);
                select[29] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe29MouseClicked

    private void labe30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe30MouseClicked
        if (select[30] == true) {
            boolean respun = false;
            respun = generarpreguntas(30);
            if (respun == true) {
                labe30.setForeground(Color.WHITE);
                select[30] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe30MouseClicked

    private void labe31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe31MouseClicked
        if (select[31] == true) {
            boolean respun = false;
            respun = generarpreguntas(31);
            if (respun == true) {
                labe31.setForeground(Color.WHITE);
                select[31] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe31MouseClicked

    private void labe32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe32MouseClicked
        if (select[32] == true) {
            boolean respun = false;
            respun = generarpreguntas(32);
            if (respun == true) {
                labe32.setForeground(Color.WHITE);
                select[32] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe32MouseClicked

    private void labe33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe33MouseClicked
        if (select[33] == true) {
            boolean respun = false;
            respun = generarpreguntas(33);
            if (respun == true) {
                labe33.setForeground(Color.WHITE);
                select[33] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe33MouseClicked

    private void labe34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe34MouseClicked
        if (select[34] == true) {
            boolean respun = false;
            respun = generarpreguntas(34);
            if (respun == true) {
                labe34.setForeground(Color.WHITE);
                select[34] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe34MouseClicked

    private void labe35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe35MouseClicked
        if (select[35] == true) {
            boolean respun = false;
            respun = generarpreguntas(35);
            if (respun == true) {
                labe35.setForeground(Color.WHITE);
                select[35] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_labe35MouseClicked

    private void labe36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe36MouseClicked
        if (select[36] == true) {
            boolean respun = false;
            respun = generarpreguntas(36);
            if (respun == true) {
                labe36.setForeground(Color.WHITE);
                select[36] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe36MouseClicked

    private void labe37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe37MouseClicked
        if (select[37] == true) {
            boolean respun = false;
            respun = generarpreguntas(37);
            if (respun == true) {
                labe37.setForeground(Color.WHITE);
                select[37] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe37MouseClicked

    private void labe38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe38MouseClicked
        if (select[38] == true) {
            boolean respun = false;
            respun = generarpreguntas(38);
            if (respun == true) {
                labe38.setForeground(Color.WHITE);
                select[38] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe38MouseClicked

    private void labe39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe39MouseClicked
        if (select[39] == true) {
            boolean respun = false;
            respun = generarpreguntas(39);
            if (respun == true) {
                labe39.setForeground(Color.WHITE);
                select[39] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe39MouseClicked

    private void labe40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe40MouseClicked
        if (select[40] == true) {
            boolean respun = false;
            respun = generarpreguntas(40);
            if (respun == true) {
                labe40.setForeground(Color.WHITE);
                select[40] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe40MouseClicked

    private void labe41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe41MouseClicked
        if (select[41] == true) {
            boolean respun = false;
            respun = generarpreguntas(41);
            if (respun == true) {
                labe41.setForeground(Color.WHITE);
                select[41] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe41MouseClicked

    private void labe42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe42MouseClicked
        if (select[42] == true) {
            boolean respun = false;
            respun = generarpreguntas(42);
            if (respun == true) {
                labe42.setForeground(Color.WHITE);
                select[42] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe42MouseClicked

    private void labe43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe43MouseClicked
        if (select[43] == true) {
            boolean respun = false;
            respun = generarpreguntas(43);
            if (respun == true) {
                labe43.setForeground(Color.WHITE);
                select[43] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe43MouseClicked

    private void labe44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labe44MouseClicked
        if (select[44] == true) {
            boolean respun = false;
            respun = generarpreguntas(44);
            if (respun == true) {
                labe44.setForeground(Color.WHITE);
                select[44] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }
    }//GEN-LAST:event_labe44MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (contadorGeneral < 6) {
            JOptionPane.showMessageDialog(rootPane, "faltan preguntas por responder");

        } else {
            close();
        }
    }//GEN-LAST:event_formWindowClosing
    boolean[] select = new boolean[45];

    // el metodo textos tiene la funcion de traer los textos de los labels que serviran para hacer preguntas,
    //son 6 label los cuales se elegiran de manera aleatoria
    public String[] textos(int numero1, int i) {
        String labels[] = new String[6];

        switch (numero1) {
            case 1:
                labels[i] = labe1.getText();
                labe1.setForeground(Color.BLACK);
                select[1] = true;

                break;
            case 2:
                labels[i] = labe2.getText();
                labe2.setForeground(Color.black);
                select[2] = true;
                break;
            case 3:
                labels[i] = labe3.getText();
                labe3.setForeground(Color.BLACK);
                select[3] = true;
                break;
            case 4:
                labels[i] = labe4.getText();
                labe4.setForeground(Color.BLACK);
                select[4] = true;
                break;
            case 5:
                labels[i] = labe5.getText();
                labe5.setForeground(Color.BLACK);
                select[5] = true;
                break;
            case 6:
                labels[i] = labe6.getText();
                labe6.setForeground(Color.BLACK);
                select[6] = true;
                break;
            case 7:
                labels[i] = labe7.getText();
                labe7.setForeground(Color.BLACK);
                select[7] = true;
                break;
            case 8:
                labels[i] = labe8.getText();
                labe8.setForeground(Color.BLACK);
                select[8] = true;
                break;
            case 9:
                labels[i] = labe9.getText();
                labe9.setForeground(Color.BLACK);
                select[9] = true;
                break;
            case 10:
                labels[i] = labe10.getText();
                labe10.setForeground(Color.BLACK);
                select[10] = true;
                break;
            case 11:
                labels[i] = labe11.getText();
                labe11.setForeground(Color.BLACK);
                select[11] = true;
                break;
            case 12:
                labels[i] = labe12.getText();
                labe12.setForeground(Color.BLACK);
                select[12] = true;
                break;
            case 13:
                labels[i] = labe13.getText();
                labe13.setForeground(Color.BLACK);
                select[13] = true;
                break;
            case 14:
                labels[i] = labe14.getText();
                labe14.setForeground(Color.BLACK);
                select[14] = true;
                break;
            case 15:
                labels[i] = labe15.getText();
                labe15.setForeground(Color.BLACK);
                select[15] = true;
                break;
            case 16:
                labels[i] = labe16.getText();
                labe16.setForeground(Color.BLACK);
                select[16] = true;
                break;
            case 17:
                labels[i] = labe17.getText();
                labe17.setForeground(Color.BLACK);
                select[17] = true;
                break;
            case 18:
                labels[i] = labe18.getText();
                labe18.setForeground(Color.BLACK);
                select[18] = true;
                break;
            case 19:
                labels[i] = labe19.getText();
                labe19.setForeground(Color.BLACK);
                select[19] = true;
                break;
            case 20:
                labels[i] = labe20.getText();
                labe20.setForeground(Color.BLACK);
                select[20] = true;
                break;
            case 21:
                labels[i] = labe21.getText();
                labe21.setForeground(Color.BLACK);
                select[21] = true;
                break;
            case 22:
                labels[i] = labe22.getText();
                labe22.setForeground(Color.BLACK);
                select[22] = true;
                break;
            case 23:
                labels[i] = labe23.getText();
                labe23.setForeground(Color.BLACK);
                select[23] = true;
                break;
            case 24:
                labels[i] = labe24.getText();
                labe24.setForeground(Color.BLACK);
                select[24] = true;
                break;
            case 25:
                labels[i] = labe25.getText();
                labe25.setForeground(Color.BLACK);
                select[25] = true;
                break;
            case 26:
                labels[i] = labe26.getText();
                labe26.setForeground(Color.BLACK);
                select[26] = true;
                break;
            case 27:
                labels[i] = labe27.getText();
                labe27.setForeground(Color.BLACK);
                select[27] = true;
                break;
            case 28:
                labels[i] = labe28.getText();
                labe28.setForeground(Color.BLACK);
                select[28] = true;
                break;
            case 29:
                labels[i] = labe29.getText();
                labe29.setForeground(Color.BLACK);
                select[29] = true;
                break;
            case 30:
                labels[i] = labe30.getText();
                labe30.setForeground(Color.BLACK);
                select[30] = true;
                break;
            case 31:
                labels[i] = labe31.getText();
                labe31.setForeground(Color.BLACK);
                select[31] = true;
                break;
            case 32:
                labels[i] = labe32.getText();
                labe32.setForeground(Color.BLACK);
                select[32] = true;
                break;
            case 33:
                labels[i] = labe33.getText();
                labe33.setForeground(Color.BLACK);
                select[33] = true;
                break;
            case 34:
                labels[i] = labe34.getText();
                labe34.setForeground(Color.BLACK);
                select[34] = true;
                break;
            case 35:
                labels[i] = labe35.getText();
                labe35.setForeground(Color.BLACK);
                select[35] = true;
                break;
            case 36:
                labels[i] = labe36.getText();
                labe36.setForeground(Color.BLACK);
                select[36] = true;
                break;
            case 37:
                labels[i] = labe37.getText();
                labe37.setForeground(Color.BLACK);
                select[37] = true;
                break;
            case 38:
                labels[i] = labe38.getText();
                labe38.setForeground(Color.BLACK);
                select[38] = true;
                break;
            case 39:
                labels[i] = labe39.getText();
                labe39.setForeground(Color.BLACK);
                select[39] = true;
                break;
            case 40:
                labels[i] = labe40.getText();
                labe40.setForeground(Color.BLACK);
                select[40] = true;
                break;
            case 41:
                labels[i] = labe41.getText();
                labe41.setForeground(Color.BLACK);
                select[41] = true;
                break;
            case 42:
                labels[i] = labe42.getText();
                labe42.setForeground(Color.BLACK);
                select[42] = true;
                break;
            case 43:
                labels[i] = labe43.getText();
                labe43.setForeground(Color.BLACK);
                select[43] = true;
                break;
            case 44:
                labels[i] = labe44.getText();
                labe44.setForeground(Color.BLACK);
                select[44] = true;
                break;

        }
        return labels;
    }
    String[] textos = new String[45];

//trae todos los textos de los labels
    public String[] traertodo() {

        textos[1] = labe1.getText() + "desde paro";
        textos[2] = labe2.getText() + "desde paro";
        textos[3] = labe3.getText() + "desde paro";
        textos[4] = labe4.getText() + "desde paro";
        textos[5] = labe5.getText() + "desde paro";
        textos[6] = labe6.getText() + "desde paro";
        textos[7] = labe7.getText() + "desde paro";
        textos[8] = labe8.getText() + "desde paro";
        textos[9] = labe9.getText() + "desde paro";
        textos[10] = labe10.getText() + "desde Paro";
        textos[11] = labe11.getText() + "desde Paro";
        textos[12] = labe12.getText() + "desde Paro";
        textos[13] = labe13.getText() + "desde Paro";
        textos[14] = labe14.getText() + "desde Paro";
        textos[15] = labe15.getText() + "desde Paro";
        textos[16] = labe16.getText() + "desde Paro";
        textos[17] = labe17.getText() + "desde Paro";
        textos[18] = labe18.getText() + "desde Paro";
        textos[19] = labe19.getText() + "desde Paro";
        textos[20] = labe20.getText() + "desde Paro";
        textos[21] = labe21.getText() + "desde Paro";
        textos[22] = labe22.getText() + "desde Paro";
        textos[23] = labe23.getText() + "desde Paro";
        textos[24] = labe24.getText() + "desde Paro";
        textos[25] = labe25.getText() + "desde Marcha";
        textos[26] = labe26.getText() + "desde Marcha";
        textos[27] = labe27.getText() + "desde Marcha";
        textos[28] = labe28.getText() + "desde Marcha";
        textos[29] = labe29.getText() + "desde Marcha";
        textos[30] = labe30.getText() + "desde Marcha";
        textos[31] = labe31.getText() + "desde Marcha";
        textos[32] = labe32.getText() + "desde Marcha";
        textos[33] = labe33.getText() + "desde Marcha";
        textos[34] = labe34.getText() + "desde Marcha";
        textos[35] = labe35.getText() + "desde Energizado";
        textos[36] = labe36.getText() + "desde Energizado";
        textos[37] = labe37.getText() + "desde Energizado";
        textos[38] = labe38.getText() + "desde Energizado";
        textos[39] = labe39.getText() + "desde Energizado";
        textos[40] = labe40.getText() + "desde Energizado";
        textos[41] = labe41.getText() + "desde Energizado";
        textos[42] = labe42.getText() + "desde Energizado";
        textos[43] = labe43.getText() + "desde Energizado";
        textos[44] = labe44.getText() + "desde Energizado";

        return textos;
    }
    //genera preguntas de manera aleatoria cogiendo la respuesta antes dada por un digito que se ingresa 
    //y otros 3 labels que sirven para ocultar la respuesta, si se da click en la respuesta correcta 
    //este devuelve un boolean con true

    public Boolean generarpreguntas(int pos) {
        Boolean resultado = false;
        Metodos generar = new Metodos();
        Stack<Integer> numero = generar.generaNumeroAleatoriosin(1, 45);
        traertodo();
        int selop[] = new int[4];
        selop[0] = pos;
        selop[1] = numero.get(0);
        selop[2] = numero.get(1);
        selop[3] = numero.get(2);
        int acert0 = 0;
        int acertar1, acertar2, acertar3, acertar4;

        if (selop[1] == pos || selop[2] == pos || selop[3] == pos) {
            selop[0] = pos;
            selop[1] = numero.get(3);
            selop[2] = numero.get(4);
            selop[3] = numero.get(5);
            Stack<Integer> pila = generar.generaNumeroAleatorio(1, 4);
            String[] options = new String[]{textos[selop[pila.get(0)]], textos[selop[pila.get(1)]], textos[selop[pila.get(2)]], textos[selop[pila.get(3)]]};
            int response = JOptionPane.showOptionDialog(null, "cual de las condiciones iniciales falta", "Title",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[0]);
            acertar1 = pila.get(0);
            acertar2 = pila.get(1);
            acertar3 = pila.get(2);
            acertar4 = pila.get(3);
            if (acertar1 == 0) {
                acert0 = 0;
            }
            if (acertar2 == 0) {
                acert0 = 1;
            }
            if (acertar3 == 0) {
                acert0 = 2;
            }
            if (acertar4 == 0) {
                acert0 = 3;
            }
            if (response == acert0) {
                JOptionPane.showMessageDialog(rootPane, "correcto");

                resultado = true;

            } else {
                JOptionPane.showMessageDialog(rootPane, "incorrecto");
                contErrores = contErrores + 1;
                resultado = false;
            }
        } else {

            Stack<Integer> pila = generar.generaNumeroAleatorio(1, 4);
            String[] options = new String[]{textos[selop[pila.get(0)]], textos[selop[pila.get(1)]], textos[selop[pila.get(2)]], textos[selop[pila.get(3)]]};
            int response = JOptionPane.showOptionDialog(null, "cual de las condiciones iniciales falta", "Title",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[0]);
            acertar1 = pila.get(0);
            acertar2 = pila.get(1);
            acertar3 = pila.get(2);
            acertar4 = pila.get(3);
            if (acertar1 == 0) {
                acert0 = 0;
            }
            if (acertar2 == 0) {
                acert0 = 1;
            }
            if (acertar3 == 0) {
                acert0 = 2;
            }
            if (acertar4 == 0) {
                acert0 = 3;
            }
            if (response == acert0) {
                JOptionPane.showMessageDialog(rootPane, "correcto");

                resultado = true;
            } else {
                JOptionPane.showMessageDialog(rootPane, "incorrecto");
                contErrores = contErrores + 1;
                resultado = false;

            }
        }

        return resultado;
    }

    private void close() {
        JOptionPane.showMessageDialog(rootPane, "Falta completar las condiciones iniciales 2");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CondicionesInicialesEva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CondicionesInicialesEva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CondicionesInicialesEva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CondicionesInicialesEva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CondicionesInicialesEva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel labe1;
    private javax.swing.JLabel labe10;
    private javax.swing.JLabel labe11;
    private javax.swing.JLabel labe12;
    private javax.swing.JLabel labe13;
    private javax.swing.JLabel labe14;
    private javax.swing.JLabel labe15;
    private javax.swing.JLabel labe16;
    private javax.swing.JLabel labe17;
    private javax.swing.JLabel labe18;
    private javax.swing.JLabel labe19;
    private javax.swing.JLabel labe2;
    private javax.swing.JLabel labe20;
    private javax.swing.JLabel labe21;
    private javax.swing.JLabel labe22;
    private javax.swing.JLabel labe23;
    private javax.swing.JLabel labe24;
    private javax.swing.JLabel labe25;
    private javax.swing.JLabel labe26;
    private javax.swing.JLabel labe27;
    private javax.swing.JLabel labe28;
    private javax.swing.JLabel labe29;
    private javax.swing.JLabel labe3;
    private javax.swing.JLabel labe30;
    private javax.swing.JLabel labe31;
    private javax.swing.JLabel labe32;
    private javax.swing.JLabel labe33;
    private javax.swing.JLabel labe34;
    private javax.swing.JLabel labe35;
    private javax.swing.JLabel labe36;
    private javax.swing.JLabel labe37;
    private javax.swing.JLabel labe38;
    private javax.swing.JLabel labe39;
    private javax.swing.JLabel labe4;
    private javax.swing.JLabel labe40;
    private javax.swing.JLabel labe41;
    private javax.swing.JLabel labe42;
    private javax.swing.JLabel labe43;
    private javax.swing.JLabel labe44;
    private javax.swing.JLabel labe5;
    private javax.swing.JLabel labe6;
    private javax.swing.JLabel labe7;
    private javax.swing.JLabel labe8;
    private javax.swing.JLabel labe9;
    private javax.swing.JLabel labelt;
    private javax.swing.JLabel labet2;
    private javax.swing.JLabel labet3;
    // End of variables declaration//GEN-END:variables
}
