/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empguadalupe.Menu.Evaluacion.arranque;

import empguadalupe.Menu.Aprendizaje.arranque.*;
import java.awt.Color;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author lzambrs
 */
public class CondicionesIniciales4 extends javax.swing.JFrame {
 int contadorGeneral;
    int contErrores;
    /**
     * Creates new form CondicionesInicialesEva
     */
    public CondicionesIniciales4() {
        initComponents();
              Metodos generar = new Metodos();

            Stack<Integer> numero = generar.generaNumeroAleatoriosin(1, 5);
            int numero1;

            String labels[] = new String[2];
            int i;
            // String label1,label2,label3,label4,label5,label6;
           
                numero1 = numero.get(1);
                labels = textos(numero1, 1);
                System.out.println(numero1);
            
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        la2 = new javax.swing.JLabel();
        la1 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        la4 = new javax.swing.JLabel();
        la3 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("GUADALUPE IV:ENCLAVAMIENTOS UNIDAD X SECUENCIA DE ARRANQUE");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 670, 30));

        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 20, 20));

        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 20, 20));

        la2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        la2.setForeground(new java.awt.Color(255, 255, 255));
        la2.setText("EQUIPO SINCRONIZADOR AUTOMATIC SIN FALLA");
        la2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                la2MouseClicked(evt);
            }
        });
        getContentPane().add(la2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 270, 20));

        la1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        la1.setForeground(new java.awt.Color(255, 255, 255));
        la1.setText("COMUNICACION CON CONTROLADOR NORMAL");
        la1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                la1MouseClicked(evt);
            }
        });
        getContentPane().add(la1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 20));

        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 340, 80));

        jLabel96.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("SISTEMA DE SINCRONIZACION LISTO");
        jLabel96.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 340, 40));

        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 20, 20));

        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 20, 20));

        la4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        la4.setForeground(new java.awt.Color(255, 255, 255));
        la4.setText("PRESION NORMAL INTERRUPTOR GENERAD");
        la4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                la4MouseClicked(evt);
            }
        });
        getContentPane().add(la4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 270, 20));

        la3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        la3.setForeground(new java.awt.Color(255, 255, 255));
        la3.setText("INTERRUPTOR DE GENERADOR ABIERTO");
        la3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                la3MouseClicked(evt);
            }
        });
        getContentPane().add(la3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, 20));

        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 340, 80));

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("SIST. INTERRUPTOR GENERADOR NORMAL");
        jLabel102.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        getContentPane().add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 340, 40));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 50, 40));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 50, 40));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("4");
        jButton3.setEnabled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 50, 40));

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 50, 40));

        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 20, 20));

        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 20, 20));

        jLabel104.setBackground(new java.awt.Color(51, 153, 255));
        jLabel104.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgfondo/color.png"))); // NOI18N
        getContentPane().add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void la1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_la1MouseClicked
 if (select[1] == true) {
            boolean respun = false;
            respun = generarpreguntas(1);
            if (respun == true) {
                la1.setForeground(Color.WHITE);
                select[1] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_la1MouseClicked

    private void la2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_la2MouseClicked
 if (select[2] == true) {
            boolean respun = false;
            respun = generarpreguntas(2);
            if (respun == true) {
                la2.setForeground(Color.WHITE);
                select[2] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_la2MouseClicked

    private void la3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_la3MouseClicked
 if (select[3] == true) {
            boolean respun = false;
            respun = generarpreguntas(3);
            if (respun == true) {
                la3.setForeground(Color.WHITE);
                select[3] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_la3MouseClicked

    private void la4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_la4MouseClicked
 if (select[4] == true) {
            boolean respun = false;
            respun = generarpreguntas(4);
            if (respun == true) {
                la4.setForeground(Color.WHITE);
                select[4] = false;
                contadorGeneral = contadorGeneral + 1;
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_la4MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         if(contadorGeneral<1){
            JOptionPane.showMessageDialog(rootPane, "faltan preguntas por responder");
            
        }else{
              dispose();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
boolean[] select = new boolean[5];

    // el metodo textos tiene la funcion de traer los textos de los labels que serviran para hacer preguntas,
    //son 6 label los cuales se elegiran de manera aleatoria
    public String[] textos(int numero1, int i) {
        String labels[] = new String[5];

        switch (numero1) {
            case 1:
                labels[i] = la1.getText();
                la1.setForeground(Color.BLACK);
                select[1] = true;

                break;
            case 2:
                labels[i] = la2.getText();
                la2.setForeground(Color.black);
                select[2] = true;
                break;
            case 3:
                labels[i] = la3.getText();
                la3.setForeground(Color.BLACK);
                select[3] = true;
                break;
            case 4:
                labels[i] = la4.getText();
                la4.setForeground(Color.BLACK);
                select[4] = true;
                break;
   
        }
        return labels;
    }
      String[] textos = new String[5];
     public String[] traertodo() {

        textos[1] = la1.getText() ;
        textos[2] = la2.getText() ;
        textos[3] = la3.getText() ;
        textos[4] = la4.getText() ;
    
  
        return textos;
    }
     public Boolean generarpreguntas(int pos) {
        Boolean resultado = false;
        Metodos generar = new Metodos();
        Stack<Integer> numero = generar.generaNumeroAleatoriosin(1, 5);
        traertodo();
        int selop[] = new int[4];
        selop[0] = pos;
        selop[1] = numero.get(0);
        selop[2] = numero.get(1);
        selop[3] = numero.get(2);
        int acert0 = 0;
        int acertar1, acertar2, acertar3, acertar4;

        if (selop[1] == pos || selop[2] == pos || selop[3] == pos) {
            selop[0] = pos;
            if (selop [1]==pos){
            selop[1] = numero.get(3);
            }
            if (selop [2]==pos){
            selop[2] = numero.get(3);
            }
            if (selop [3]==pos){
            selop[3] = numero.get(3);
            }
            
            Stack<Integer> pila = generar.generaNumeroAleatorio(1, 4);
            String[] options = new String[]{textos[selop[pila.get(0)]], textos[selop[pila.get(1)]], textos[selop[pila.get(2)]], textos[selop[pila.get(3)]]};
            int response = JOptionPane.showOptionDialog(null, "cual de las condiciones iniciales falta", "Title",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[0]);
            acertar1 = pila.get(0);
            acertar2 = pila.get(1);
            acertar3 = pila.get(2);
            acertar4 = pila.get(3);
            if (acertar1 == 0) {
                acert0 = 0;
            }
            if (acertar2 == 0) {
                acert0 = 1;
            }
            if (acertar3 == 0) {
                acert0 = 2;
            }
            if (acertar4 == 0) {
                acert0 = 3;
            }
            if (response == acert0) {
                JOptionPane.showMessageDialog(rootPane, "correcto");
           
                resultado = true;

            } else {
                JOptionPane.showMessageDialog(rootPane, "incorrecto");
                contErrores=contErrores+1;
                resultado = false;
            }
        } else {

            Stack<Integer> pila = generar.generaNumeroAleatorio(1, 4);
            String[] options = new String[]{textos[selop[pila.get(0)]], textos[selop[pila.get(1)]], textos[selop[pila.get(2)]], textos[selop[pila.get(3)]]};
            int response = JOptionPane.showOptionDialog(null, "cual de las condiciones iniciales falta", "Title",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[0]);
            acertar1 = pila.get(0);
            acertar2 = pila.get(1);
            acertar3 = pila.get(2);
            acertar4 = pila.get(3);
            if (acertar1 == 0) {
                acert0 = 0;
            }
            if (acertar2 == 0) {
                acert0 = 1;
            }
            if (acertar3 == 0) {
                acert0 = 2;
            }
            if (acertar4 == 0) {
                acert0 = 3;
            }
            if (response == acert0) {
                JOptionPane.showMessageDialog(rootPane, "correcto");
              
                resultado = true;
            } else {
                JOptionPane.showMessageDialog(rootPane, "incorrecto");
                contErrores=contErrores+1;
                resultado = false;
                 
            }
        }

        return resultado;
    }
 

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CondicionesIniciales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CondicionesIniciales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CondicionesIniciales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CondicionesIniciales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CondicionesIniciales4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel la1;
    private javax.swing.JLabel la2;
    private javax.swing.JLabel la3;
    private javax.swing.JLabel la4;
    // End of variables declaration//GEN-END:variables
}
